# AUTOGENERATED CONFIG - NOUGAT V3
SELECTION_METHOD="default"
SCREENSHOT_DIRECTORY="$HOME/Pictures/Screenshots"
SCREENCAST_DIRECTORY="$HOME/Videos/Screencasts"
ORGANIZATION_POLICY='${year}/${month}/${day}/${hour}:${minute}:${second}'
