#!/bin/bash

# DO NOT SHARE YOUR KEY
key=Ah60cLKhbFqwEakJGZpgLGeJjiGJ55cODLmdlLbe34HbaDDC70kEugUd74sOwv30
# Log URLs
log=false
# Log file location (if relevant)
logfile="$HOME/.pstepw"
# Copy links to clipboard after upload (requires xclip)
clipboard=true
# Send a notification when done
notify=true
# Open URL in browser
browser=true
